### ISSUE TITLE
Scrollpane setVvalue units?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#4]
I can’t find explanations on the setVvalue(1.0) for Scrollpane in the JavaFx Tutorial. What does 1.0 refer to, or do, for the scrollpane vertical value? What is this value “1.0” to be interpreted as?

**Comment by tjtanjin** [comment]
Hello Mr. Gwee! I'm an ex-student of the CS2103T module dropping in to see if I can be of any help. With regards to your question, you may find the following description to be helpful:

![image](https://user-images.githubusercontent.com/43908963/151739837-f4226853-0b2b-4b32-9610-094d5bddd286.png)

To add on, I found the above documentation at the first link below which you may be interested to explore more. The second link contains documentation with regards to javafx geometry which may be useful for understanding relevant terms in the description above:
- https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/ScrollPane.html
- https://docs.oracle.com/javase/8/javafx/api/javafx/geometry/Bounds.html

I hope the above information helps - otherwise please feel free to reach out again :)

**Comment by gweeyc** [comment]
Hi ijtanjin,
                 Much thanks for all the tips and help you've posted for my questions. I will follow up with them, any further queries i'll raise again a query if I cannot find them online.
