### ISSUE TITLE
Text Field shrink on the 4th conversation

### ISSUE THREAD

**Issue by lowyanshuang** [nus-tic4002-AY2122s2/forum#5]
The text is showing nicely in the first 3 conversation. But when it reaches the 4th one, i can only see the first line. Please refer to the images.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/54314980/152360263-4feccb32-679c-44a8-a391-7818f3d70fe5.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/54314980/152360284-ff107952-9ef7-4039-858d-7b676f5e45b8.png)

**Comment by Javiier-pzk** [comment]
Hi Mr Low! I'm an ex-student of the CS2103T module dropping in to see if I can be of any help.
You are facing this issue because you did not set the `minHeight` of your`DialogBox` class, as a result, your dialogs are being truncated when they reach the end of your chatbox.

This line should fix your problems:
```java
dialog.setMinHeight(Region.USE_PREF_SIZE);
```
You can add this line in the constructor of your `DialogBox` class

**Comment by lowyanshuang** [comment]
Got it! Thank you, I will try it out :)

**Comment by litone01** [comment]
Hi Mr Low! I'm an ex-student of the CS2103/T module dropping in to see if I can be of any help.

Just a gentle reminder to close this issue if the problem has been resolved. You can do so by clicking at the button at the bottom of this page, indicating something like `close this issue`.

If not resolved yet, please kindly post a comment explaining which part of the problem/question remains unresolved, and we will try our best to help to resolve the issue:)

Thanks for your understanding:)

**Comment by lowyanshuang** [comment]
@litone01 thank you for your remainder, i forget to close it.
